### ISSUE TITLE
[BUG] Cannot connect to server when set `playerInfoForwardingMode` set to `modern`

### ISSUE THREAD

**Issue by lgc2333** [Elytrium/LimboAPI#98]
**Describe the bug**

Cannot connect to SERVER (not proxy) when set `player-info-forwarding-mode` set to `modern` (maybe with Geyser & floodgate?)

It shows error
```
[10:02:05 ERROR]: [connected player] student_2333 (/***:9073): disconnected while connecting to main: velocity.error.modern-forwarding-failed
[10:02:05 INFO]: [connected player] student_2333 (/***:9073) has disconnected: 无法连接至 main：您的服务器未向代理服务器转发请求，请确保已配置 Velocity 转发。
```

Error exists when `prepare-min-version` set to `1_13`

Relative to https://github.com/GeyserMC/Floodgate/issues/416

**To Reproduce**
1. set `player-info-forwarding-mode` to `modern` in Velocity config
2. connect to proxy

**Expected behavior**
successfully connect to server

**Screenshots**
null

**Server Info (please complete the following information):**

- **Velocity** 3.2.0-SNAPSHOT (git-bda1430d-b259)
- **LimboAPI** 1.1.13
- **LimboAuth** 1.1.12
- **LimboFilter** 1.1.10

<details>
<summary>Velocity Dump</summary>

```json
{
  "versionInfo": {
    "name": "Velocity",
    "vendor": "Velocity Contributors",
    "version": "3.2.0-SNAPSHOT (git-bda1430d-b259)"
  },
  "platform": {
    "operatingSystemType": "Windows Server 2022",
    "operatingSystemVersion": "10.0",
    "operatingSystemArchitecture": "amd64",
    "javaVersion": "17.0.6",
    "javaVendor": "Oracle Corporation",
    "listener": {
      "listenerType": "NIO",
      "compression": "Java",
      "encryption": "Java"
    }
  },
  "config": {
    "bind": "0.0.0.0:22010",
    "motd": "打我服务器没妈妈",
    "showMaxPlayers": 250,
    "onlineMode": false,
    "preventClientProxyConnections": false,
    "playerInfoForwardingMode": "MODERN",
    "announceForge": false,
    "onlineModeKickExistingPlayers": false,
    "pingPassthrough": "ALL",
    "advanced": {
      "compressionThreshold": 256,
      "compressionLevel": -1,
      "loginRatelimit": 3000,
      "connectionTimeout": 5000,
      "readTimeout": 30000,
      "proxyProtocol": false,
      "tcpFastOpen": false,
      "bungeePluginMessageChannel": true,
      "showPingRequests": false,
      "failoverOnUnexpectedServerDisconnect": true,
      "announceProxyCommands": true,
      "logCommandExecutions": true,
      "logPlayerConnections": true
    },
    "query": {
      "queryEnabled": true,
      "queryPort": 22010,
      "queryMap": "Velocity",
      "showPlugins": true
    },
    "enablePlayerAddressLogging": true,
    "forceKeyAuthentication": true,
    "servers": {
      "main": {
        "currentPlayers": 0,
        "host": "127.0.0.1",
        "port": 25565
      }
    },
    "connectOrder": [
      "main"
    ],
    "forcedHosts": {}
  },
  "plugins": [
    {
      "id": "allmusic",
      "name": "AllMusic",
      "version": "2.18.8",
      "authors": [
        "Color_yr"
      ],
      "description": "全服点歌插件",
      "url": "https://github.com/Coloryr/AllMusic_P"
    },
    {
      "id": "floodgate",
      "name": "floodgate",
      "version": "2.2.2-SNAPSHOT (b88-2278589)",
      "authors": [
        "GeyserMC"
      ],
      "description": "Allows Bedrock players to join Java edition servers while keeping the server in online mode",
      "url": "https://geysermc.org}"
    },
    {
      "id": "geyser",
      "name": "Geyser-Velocity",
      "version": "2.1.2-SNAPSHOT (git-master-c1d8009)",
      "authors": [
        "GeyserMC"
      ],
      "url": "https://geysermc.org"
    },
    {
      "id": "limboapi",
      "name": "LimboAPI",
      "version": "1.1.13",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "Velocity plugin for making virtual servers.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboauth",
      "name": "LimboAuth",
      "version": "1.1.12",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi",
        "floodgate"
      ]
    },
    {
      "id": "limbofilter",
      "name": "LimboFilter",
      "version": "1.1.10",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi"
      ]
    },
    {
      "id": "luckperms",
      "name": "LuckPerms",
      "version": "5.4.98",
      "authors": [
        "Luck"
      ],
      "description": "A permissions plugin",
      "url": "https://luckperms.net"
    },
    {
      "id": "serverutils",
      "name": "ServerUtils",
      "version": "3.5.4",
      "authors": [
        "FrankHeijden"
      ],
      "description": "A server utility",
      "url": "https://github.com/FrankHeijden/ServerUtils"
    }
  ]
}
```

</details>

<details>
<summary>LimboAPI config</summary>

```yml
version: "1.1.13"
serializer: LEGACY_AMPERSAND
prefix: "LimboAPI &6>>&f"

main:
  check-for-updates: false
  max-chat-message-length: 256
  max-unknown-packet-length: 2048
  max-single-generic-packet-length: 4096
  max-multi-generic-packet-length: 131072
  max-packet-length-to-suppress-it: 512
  discard-compression-on-login: false
  discard-compression-after-login: false
  save-uncompressed-packets: true
  logging-enabled: true
  prepare-min-version: "1_7_2"
  prepare-max-version: "LATEST"
  pre-limbo-profile-request-plugins:
    - "floodgate"
    - "geyser"
  auto-regenerate-listeners: false
  reduced-debug-info: false
  view-distance: 16
  simulation-distance: 12
  chunk-radius-send-on-spawn: 2
  chunks-per-tick: 16
  messages:
    too-big-packet: "{PRFX}{NL}{NL}&cYour client sent too big packet!"
    invalid-ping: "{PRFX}{NL}{NL}&cYour client sent invalid ping packet!"
    time-out: "{PRFX}{NL}{NL}操作超时"
```

</details>

**Additional context**
null
